[{"TimeUTC":"2025-01-17 10:08:47","timestampInMs":1737108527096,"requestPath":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app/favicon.ico","requestMethod":"GET","responseStatusCode":-1,"requestId":"42m6k-1737108526031-9456c3307ad3","requestUserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main.py","host":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentDomain":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentId":"dpl_DBBgxg2cVb9usJtdDVjRC4ex6Ttk","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/main.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, jsonify\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_nLtmkWiHzW9EPv20LiLufmtG1LNk"},{"TimeUTC":"2025-01-17 10:08:46","timestampInMs":1737108526091,"requestPath":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app/favicon.ico","requestMethod":"GET","responseStatusCode":500,"requestId":"42m6k-1737108526031-9456c3307ad3","requestUserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main.py","host":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentDomain":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentId":"dpl_DBBgxg2cVb9usJtdDVjRC4ex6Ttk","durationMs":987,"region":"iad1","maxMemoryUsed":62,"memorySize":1024,"message":"","projectId":"prj_nLtmkWiHzW9EPv20LiLufmtG1LNk"},{"TimeUTC":"2025-01-17 10:08:45","timestampInMs":1737108525523,"requestPath":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app/","requestMethod":"GET","responseStatusCode":-1,"requestId":"8z6px-1737108524466-2ad2f85f384e","requestUserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main.py","host":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentDomain":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentId":"dpl_DBBgxg2cVb9usJtdDVjRC4ex6Ttk","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/main.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, jsonify\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_nLtmkWiHzW9EPv20LiLufmtG1LNk"},{"TimeUTC":"2025-01-17 10:08:44","timestampInMs":1737108524530,"requestPath":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app/","requestMethod":"GET","responseStatusCode":500,"requestId":"8z6px-1737108524466-2ad2f85f384e","requestUserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main.py","host":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentDomain":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentId":"dpl_DBBgxg2cVb9usJtdDVjRC4ex6Ttk","durationMs":977,"region":"iad1","maxMemoryUsed":62,"memorySize":1024,"message":"","projectId":"prj_nLtmkWiHzW9EPv20LiLufmtG1LNk"},{"TimeUTC":"2025-01-17 10:07:35","timestampInMs":1737108455965,"requestPath":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app/favicon.ico","requestMethod":"GET","responseStatusCode":-1,"requestId":"tk2l7-1737108454887-0313f82bbcbf","requestUserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main.py","host":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentDomain":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentId":"dpl_DBBgxg2cVb9usJtdDVjRC4ex6Ttk","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/main.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, jsonify\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_nLtmkWiHzW9EPv20LiLufmtG1LNk"},{"TimeUTC":"2025-01-17 10:07:34","timestampInMs":1737108454943,"requestPath":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app/favicon.ico","requestMethod":"GET","responseStatusCode":500,"requestId":"tk2l7-1737108454887-0313f82bbcbf","requestUserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main.py","host":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentDomain":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentId":"dpl_DBBgxg2cVb9usJtdDVjRC4ex6Ttk","durationMs":1003,"region":"iad1","maxMemoryUsed":62,"memorySize":1024,"message":"","projectId":"prj_nLtmkWiHzW9EPv20LiLufmtG1LNk"},{"TimeUTC":"2025-01-17 10:07:34","timestampInMs":1737108454724,"requestPath":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app/","requestMethod":"GET","responseStatusCode":-1,"requestId":"grq9t-1737108453625-cc39f5d48df1","requestUserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main.py","host":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentDomain":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentId":"dpl_DBBgxg2cVb9usJtdDVjRC4ex6Ttk","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/main.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, jsonify\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_nLtmkWiHzW9EPv20LiLufmtG1LNk"},{"TimeUTC":"2025-01-17 10:07:33","timestampInMs":1737108453688,"requestPath":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app/","requestMethod":"GET","responseStatusCode":500,"requestId":"grq9t-1737108453625-cc39f5d48df1","requestUserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main.py","host":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentDomain":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentId":"dpl_DBBgxg2cVb9usJtdDVjRC4ex6Ttk","durationMs":1020,"region":"iad1","maxMemoryUsed":62,"memorySize":1024,"message":"","projectId":"prj_nLtmkWiHzW9EPv20LiLufmtG1LNk"},{"TimeUTC":"2025-01-17 10:06:53","timestampInMs":1737108413737,"requestPath":"jadexi.vercel.app/favicon.ico","requestMethod":"GET","responseStatusCode":-1,"requestId":"7vshc-1737108412542-52b711c56632","requestUserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main.py","host":"jadexi.vercel.app","deploymentDomain":"jadexi.vercel.app","deploymentId":"dpl_DBBgxg2cVb9usJtdDVjRC4ex6Ttk","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/main.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, jsonify\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_nLtmkWiHzW9EPv20LiLufmtG1LNk"},{"TimeUTC":"2025-01-17 10:06:52","timestampInMs":1737108412710,"requestPath":"jadexi.vercel.app/favicon.ico","requestMethod":"GET","responseStatusCode":500,"requestId":"7vshc-1737108412542-52b711c56632","requestUserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main.py","host":"jadexi.vercel.app","deploymentDomain":"jadexi.vercel.app","deploymentId":"dpl_DBBgxg2cVb9usJtdDVjRC4ex6Ttk","durationMs":1013,"region":"iad1","maxMemoryUsed":62,"memorySize":1024,"message":"","projectId":"prj_nLtmkWiHzW9EPv20LiLufmtG1LNk"},{"TimeUTC":"2025-01-17 10:06:49","timestampInMs":1737108409199,"requestPath":"jadexi-jadexelis-projects.vercel.app/","requestMethod":"GET","responseStatusCode":-1,"requestId":"qhf7t-1737108407710-6261ff60657b","requestUserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main.py","host":"jadexi-jadexelis-projects.vercel.app","deploymentDomain":"jadexi-jadexelis-projects.vercel.app","deploymentId":"dpl_DBBgxg2cVb9usJtdDVjRC4ex6Ttk","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/main.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, jsonify\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_nLtmkWiHzW9EPv20LiLufmtG1LNk"},{"TimeUTC":"2025-01-17 10:06:48","timestampInMs":1737108408162,"requestPath":"jadexi-jadexelis-projects.vercel.app/","requestMethod":"GET","responseStatusCode":500,"requestId":"qhf7t-1737108407710-6261ff60657b","requestUserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main.py","host":"jadexi-jadexelis-projects.vercel.app","deploymentDomain":"jadexi-jadexelis-projects.vercel.app","deploymentId":"dpl_DBBgxg2cVb9usJtdDVjRC4ex6Ttk","durationMs":1018,"region":"iad1","maxMemoryUsed":62,"memorySize":1024,"message":"","projectId":"prj_nLtmkWiHzW9EPv20LiLufmtG1LNk"},{"TimeUTC":"2025-01-17 10:06:43","timestampInMs":1737108403643,"requestPath":"jadexi.vercel.app/","requestMethod":"GET","responseStatusCode":-1,"requestId":"q8tdj-1737108402209-984a8687389a","requestUserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main.py","host":"jadexi.vercel.app","deploymentDomain":"jadexi.vercel.app","deploymentId":"dpl_DBBgxg2cVb9usJtdDVjRC4ex6Ttk","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/main.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, jsonify\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_nLtmkWiHzW9EPv20LiLufmtG1LNk"},{"TimeUTC":"2025-01-17 10:06:42","timestampInMs":1737108402616,"requestPath":"jadexi.vercel.app/","requestMethod":"GET","responseStatusCode":500,"requestId":"q8tdj-1737108402209-984a8687389a","requestUserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main.py","host":"jadexi.vercel.app","deploymentDomain":"jadexi.vercel.app","deploymentId":"dpl_DBBgxg2cVb9usJtdDVjRC4ex6Ttk","durationMs":1008,"region":"iad1","maxMemoryUsed":62,"memorySize":1024,"message":"","projectId":"prj_nLtmkWiHzW9EPv20LiLufmtG1LNk"},{"TimeUTC":"2025-01-17 10:06:24","timestampInMs":1737108384456,"requestPath":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app/favicon.png","requestMethod":"GET","responseStatusCode":-1,"requestId":"wklmj-1737108383407-53826fe4738d","requestUserAgent":"Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0 Mobile/15E148 Safari/604.1","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main.py","host":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentDomain":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentId":"dpl_DBBgxg2cVb9usJtdDVjRC4ex6Ttk","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/main.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, jsonify\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_nLtmkWiHzW9EPv20LiLufmtG1LNk"},{"TimeUTC":"2025-01-17 10:06:23","timestampInMs":1737108383446,"requestPath":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app/favicon.png","requestMethod":"GET","responseStatusCode":500,"requestId":"wklmj-1737108383407-53826fe4738d","requestUserAgent":"Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0 Mobile/15E148 Safari/604.1","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main.py","host":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentDomain":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentId":"dpl_DBBgxg2cVb9usJtdDVjRC4ex6Ttk","durationMs":995,"region":"iad1","maxMemoryUsed":62,"memorySize":1024,"message":"","projectId":"prj_nLtmkWiHzW9EPv20LiLufmtG1LNk"},{"TimeUTC":"2025-01-17 10:06:21","timestampInMs":1737108381342,"requestPath":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app/favicon.png","requestMethod":"GET","responseStatusCode":-1,"requestId":"qrhnw-1737108380280-927acb34d09d","requestUserAgent":"Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0 Mobile/15E148 Safari/604.1","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main.py","host":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentDomain":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentId":"dpl_DBBgxg2cVb9usJtdDVjRC4ex6Ttk","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/main.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, jsonify\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_nLtmkWiHzW9EPv20LiLufmtG1LNk"},{"TimeUTC":"2025-01-17 10:06:20","timestampInMs":1737108380325,"requestPath":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app/favicon.png","requestMethod":"GET","responseStatusCode":500,"requestId":"qrhnw-1737108380280-927acb34d09d","requestUserAgent":"Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0 Mobile/15E148 Safari/604.1","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main.py","host":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentDomain":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentId":"dpl_DBBgxg2cVb9usJtdDVjRC4ex6Ttk","durationMs":999,"region":"iad1","maxMemoryUsed":62,"memorySize":1024,"message":"","projectId":"prj_nLtmkWiHzW9EPv20LiLufmtG1LNk"},{"TimeUTC":"2025-01-17 10:06:19","timestampInMs":1737108379181,"requestPath":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app/favicon.png","requestMethod":"GET","responseStatusCode":-1,"requestId":"bcvk6-1737108378119-baacfd66e5e8","requestUserAgent":"Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0 Mobile/15E148 Safari/604.1","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main.py","host":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentDomain":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentId":"dpl_DBBgxg2cVb9usJtdDVjRC4ex6Ttk","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/main.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, jsonify\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_nLtmkWiHzW9EPv20LiLufmtG1LNk"},{"TimeUTC":"2025-01-17 10:06:18","timestampInMs":1737108378160,"requestPath":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app/favicon.png","requestMethod":"GET","responseStatusCode":500,"requestId":"bcvk6-1737108378119-baacfd66e5e8","requestUserAgent":"Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0 Mobile/15E148 Safari/604.1","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main.py","host":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentDomain":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentId":"dpl_DBBgxg2cVb9usJtdDVjRC4ex6Ttk","durationMs":1004,"region":"iad1","maxMemoryUsed":62,"memorySize":1024,"message":"","projectId":"prj_nLtmkWiHzW9EPv20LiLufmtG1LNk"},{"TimeUTC":"2025-01-17 10:06:18","timestampInMs":1737108378078,"requestPath":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app/favicon.ico","requestMethod":"GET","responseStatusCode":-1,"requestId":"7pgg6-1737108377005-034eeb69986c","requestUserAgent":"Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0 Mobile/15E148 Safari/604.1","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main.py","host":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentDomain":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentId":"dpl_DBBgxg2cVb9usJtdDVjRC4ex6Ttk","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/main.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, jsonify\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_nLtmkWiHzW9EPv20LiLufmtG1LNk"},{"TimeUTC":"2025-01-17 10:06:17","timestampInMs":1737108377048,"requestPath":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app/favicon.ico","requestMethod":"GET","responseStatusCode":500,"requestId":"7pgg6-1737108377005-034eeb69986c","requestUserAgent":"Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0 Mobile/15E148 Safari/604.1","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main.py","host":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentDomain":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentId":"dpl_DBBgxg2cVb9usJtdDVjRC4ex6Ttk","durationMs":1015,"region":"iad1","maxMemoryUsed":62,"memorySize":1024,"message":"","projectId":"prj_nLtmkWiHzW9EPv20LiLufmtG1LNk"},{"TimeUTC":"2025-01-17 10:06:14","timestampInMs":1737108374417,"requestPath":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app/favicon.ico","requestMethod":"GET","responseStatusCode":-1,"requestId":"dls4w-1737108373349-248464e55b26","requestUserAgent":"Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0 Mobile/15E148 Safari/604.1","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main.py","host":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentDomain":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentId":"dpl_DBBgxg2cVb9usJtdDVjRC4ex6Ttk","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/main.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, jsonify\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_nLtmkWiHzW9EPv20LiLufmtG1LNk"},{"TimeUTC":"2025-01-17 10:06:13","timestampInMs":1737108373383,"requestPath":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app/favicon.ico","requestMethod":"GET","responseStatusCode":500,"requestId":"dls4w-1737108373349-248464e55b26","requestUserAgent":"Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0 Mobile/15E148 Safari/604.1","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main.py","host":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentDomain":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentId":"dpl_DBBgxg2cVb9usJtdDVjRC4ex6Ttk","durationMs":1015,"region":"iad1","maxMemoryUsed":62,"memorySize":1024,"message":"","projectId":"prj_nLtmkWiHzW9EPv20LiLufmtG1LNk"},{"TimeUTC":"2025-01-17 10:06:12","timestampInMs":1737108372283,"requestPath":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app/favicon.ico","requestMethod":"GET","responseStatusCode":-1,"requestId":"8nvq7-1737108371210-bd8cd83cb7ac","requestUserAgent":"Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0 Mobile/15E148 Safari/604.1","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main.py","host":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentDomain":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentId":"dpl_DBBgxg2cVb9usJtdDVjRC4ex6Ttk","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/main.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, jsonify\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_nLtmkWiHzW9EPv20LiLufmtG1LNk"},{"TimeUTC":"2025-01-17 10:06:11","timestampInMs":1737108371251,"requestPath":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app/favicon.ico","requestMethod":"GET","responseStatusCode":500,"requestId":"8nvq7-1737108371210-bd8cd83cb7ac","requestUserAgent":"Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0 Mobile/15E148 Safari/604.1","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main.py","host":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentDomain":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentId":"dpl_DBBgxg2cVb9usJtdDVjRC4ex6Ttk","durationMs":1014,"region":"iad1","maxMemoryUsed":62,"memorySize":1024,"message":"","projectId":"prj_nLtmkWiHzW9EPv20LiLufmtG1LNk"},{"TimeUTC":"2025-01-17 10:06:11","timestampInMs":1737108371057,"requestPath":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app/","requestMethod":"GET","responseStatusCode":-1,"requestId":"5hq9c-1737108369976-68a1fccd6dbb","requestUserAgent":"Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0 Mobile/15E148 Safari/604.1","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main.py","host":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentDomain":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentId":"dpl_DBBgxg2cVb9usJtdDVjRC4ex6Ttk","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/main.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, jsonify\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_nLtmkWiHzW9EPv20LiLufmtG1LNk"},{"TimeUTC":"2025-01-17 10:06:10","timestampInMs":1737108370011,"requestPath":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app/","requestMethod":"GET","responseStatusCode":500,"requestId":"5hq9c-1737108369976-68a1fccd6dbb","requestUserAgent":"Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0 Mobile/15E148 Safari/604.1","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main.py","host":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentDomain":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentId":"dpl_DBBgxg2cVb9usJtdDVjRC4ex6Ttk","durationMs":1031,"region":"iad1","maxMemoryUsed":62,"memorySize":1024,"message":"","projectId":"prj_nLtmkWiHzW9EPv20LiLufmtG1LNk"},{"TimeUTC":"2025-01-17 10:06:08","timestampInMs":1737108368937,"requestPath":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app/","requestMethod":"GET","responseStatusCode":-1,"requestId":"vjl4p-1737108367837-dd170fa56f2c","requestUserAgent":"Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0 Mobile/15E148 Safari/604.1","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main.py","host":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentDomain":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentId":"dpl_DBBgxg2cVb9usJtdDVjRC4ex6Ttk","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/main.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, jsonify\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_nLtmkWiHzW9EPv20LiLufmtG1LNk"},{"TimeUTC":"2025-01-17 10:06:07","timestampInMs":1737108367876,"requestPath":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app/","requestMethod":"GET","responseStatusCode":500,"requestId":"vjl4p-1737108367837-dd170fa56f2c","requestUserAgent":"Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0 Mobile/15E148 Safari/604.1","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main.py","host":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentDomain":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentId":"dpl_DBBgxg2cVb9usJtdDVjRC4ex6Ttk","durationMs":1034,"region":"iad1","maxMemoryUsed":62,"memorySize":1024,"message":"","projectId":"prj_nLtmkWiHzW9EPv20LiLufmtG1LNk"},{"TimeUTC":"2025-01-17 10:05:57","timestampInMs":1737108357428,"requestPath":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app/favicon.ico","requestMethod":"GET","responseStatusCode":-1,"requestId":"6kpm5-1737108356370-ed24491a69c4","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main.py","host":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentDomain":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentId":"dpl_DBBgxg2cVb9usJtdDVjRC4ex6Ttk","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/main.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, jsonify\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_nLtmkWiHzW9EPv20LiLufmtG1LNk"},{"TimeUTC":"2025-01-17 10:05:57","timestampInMs":1737108357397,"requestPath":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app/favicon.ico","requestMethod":"GET","responseStatusCode":-1,"requestId":"mftkv-1737108356296-e6d79e9f5810","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main.py","host":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentDomain":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentId":"dpl_DBBgxg2cVb9usJtdDVjRC4ex6Ttk","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/main.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, jsonify\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_nLtmkWiHzW9EPv20LiLufmtG1LNk"},{"TimeUTC":"2025-01-17 10:05:56","timestampInMs":1737108356408,"requestPath":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app/favicon.ico","requestMethod":"GET","responseStatusCode":500,"requestId":"6kpm5-1737108356370-ed24491a69c4","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main.py","host":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentDomain":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentId":"dpl_DBBgxg2cVb9usJtdDVjRC4ex6Ttk","durationMs":1005,"region":"iad1","maxMemoryUsed":62,"memorySize":1024,"message":"","projectId":"prj_nLtmkWiHzW9EPv20LiLufmtG1LNk"},{"TimeUTC":"2025-01-17 10:05:56","timestampInMs":1737108356335,"requestPath":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app/favicon.ico","requestMethod":"GET","responseStatusCode":500,"requestId":"mftkv-1737108356296-e6d79e9f5810","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main.py","host":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentDomain":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentId":"dpl_DBBgxg2cVb9usJtdDVjRC4ex6Ttk","durationMs":1044,"region":"iad1","maxMemoryUsed":32,"memorySize":1024,"message":"","projectId":"prj_nLtmkWiHzW9EPv20LiLufmtG1LNk"},{"TimeUTC":"2025-01-17 10:05:56","timestampInMs":1737108356114,"requestPath":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app/","requestMethod":"GET","responseStatusCode":-1,"requestId":"h78fq-1737108354915-688dac1f0feb","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main.py","host":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentDomain":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentId":"dpl_DBBgxg2cVb9usJtdDVjRC4ex6Ttk","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/main.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, jsonify\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.\nTraceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/main.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, jsonify\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_nLtmkWiHzW9EPv20LiLufmtG1LNk"},{"TimeUTC":"2025-01-17 10:05:55","timestampInMs":1737108355998,"requestPath":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app/","requestMethod":"GET","responseStatusCode":-1,"requestId":"8j6nm-1737108354914-3b5f5b46bb2a","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main.py","host":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentDomain":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentId":"dpl_DBBgxg2cVb9usJtdDVjRC4ex6Ttk","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/main.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, jsonify\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_nLtmkWiHzW9EPv20LiLufmtG1LNk"},{"TimeUTC":"2025-01-17 10:05:55","timestampInMs":1737108355592,"requestPath":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app/favicon.ico","requestMethod":"GET","responseStatusCode":-1,"requestId":"5mxvw-1737108354429-98b46a98cdbb","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main.py","host":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentDomain":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentId":"dpl_DBBgxg2cVb9usJtdDVjRC4ex6Ttk","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/main.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, jsonify\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_nLtmkWiHzW9EPv20LiLufmtG1LNk"},{"TimeUTC":"2025-01-17 10:05:55","timestampInMs":1737108355074,"requestPath":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app/","requestMethod":"GET","responseStatusCode":500,"requestId":"h78fq-1737108354915-688dac1f0feb","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main.py","host":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentDomain":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentId":"dpl_DBBgxg2cVb9usJtdDVjRC4ex6Ttk","durationMs":1017,"region":"iad1","maxMemoryUsed":32,"memorySize":1024,"message":"","projectId":"prj_nLtmkWiHzW9EPv20LiLufmtG1LNk"},{"TimeUTC":"2025-01-17 10:05:54","timestampInMs":1737108354948,"requestPath":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app/","requestMethod":"GET","responseStatusCode":500,"requestId":"8j6nm-1737108354914-3b5f5b46bb2a","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main.py","host":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentDomain":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentId":"dpl_DBBgxg2cVb9usJtdDVjRC4ex6Ttk","durationMs":1031,"region":"iad1","maxMemoryUsed":62,"memorySize":1024,"message":"","projectId":"prj_nLtmkWiHzW9EPv20LiLufmtG1LNk"},{"TimeUTC":"2025-01-17 10:05:54","timestampInMs":1737108354797,"requestPath":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app/","requestMethod":"GET","responseStatusCode":-1,"requestId":"t6vn4-1737108353712-503351e058dc","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main.py","host":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentDomain":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentId":"dpl_DBBgxg2cVb9usJtdDVjRC4ex6Ttk","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/main.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, jsonify\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_nLtmkWiHzW9EPv20LiLufmtG1LNk"},{"TimeUTC":"2025-01-17 10:05:54","timestampInMs":1737108354560,"requestPath":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app/favicon.ico","requestMethod":"GET","responseStatusCode":500,"requestId":"5mxvw-1737108354429-98b46a98cdbb","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main.py","host":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentDomain":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentId":"dpl_DBBgxg2cVb9usJtdDVjRC4ex6Ttk","durationMs":1015,"region":"iad1","maxMemoryUsed":62,"memorySize":1024,"message":"","projectId":"prj_nLtmkWiHzW9EPv20LiLufmtG1LNk"},{"TimeUTC":"2025-01-17 10:05:54","timestampInMs":1737108354407,"requestPath":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app/favicon.ico","requestMethod":"GET","responseStatusCode":-1,"requestId":"755gp-1737108353225-da6d8556cf32","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main.py","host":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentDomain":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentId":"dpl_DBBgxg2cVb9usJtdDVjRC4ex6Ttk","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/main.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, jsonify\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_nLtmkWiHzW9EPv20LiLufmtG1LNk"},{"TimeUTC":"2025-01-17 10:05:54","timestampInMs":1737108354257,"requestPath":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app/","requestMethod":"GET","responseStatusCode":-1,"requestId":"8qhm7-1737108353058-72f32297e974","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main.py","host":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentDomain":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentId":"dpl_DBBgxg2cVb9usJtdDVjRC4ex6Ttk","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/main.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, jsonify\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_nLtmkWiHzW9EPv20LiLufmtG1LNk"},{"TimeUTC":"2025-01-17 10:05:53","timestampInMs":1737108353749,"requestPath":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app/","requestMethod":"GET","responseStatusCode":500,"requestId":"t6vn4-1737108353712-503351e058dc","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main.py","host":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentDomain":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentId":"dpl_DBBgxg2cVb9usJtdDVjRC4ex6Ttk","durationMs":1032,"region":"iad1","maxMemoryUsed":62,"memorySize":1024,"message":"","projectId":"prj_nLtmkWiHzW9EPv20LiLufmtG1LNk"},{"TimeUTC":"2025-01-17 10:05:53","timestampInMs":1737108353379,"requestPath":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app/favicon.ico","requestMethod":"GET","responseStatusCode":500,"requestId":"755gp-1737108353225-da6d8556cf32","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main.py","host":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentDomain":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentId":"dpl_DBBgxg2cVb9usJtdDVjRC4ex6Ttk","durationMs":1014,"region":"iad1","maxMemoryUsed":62,"memorySize":1024,"message":"","projectId":"prj_nLtmkWiHzW9EPv20LiLufmtG1LNk"},{"TimeUTC":"2025-01-17 10:05:53","timestampInMs":1737108353209,"requestPath":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app/","requestMethod":"GET","responseStatusCode":500,"requestId":"8qhm7-1737108353058-72f32297e974","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main.py","host":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentDomain":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentId":"dpl_DBBgxg2cVb9usJtdDVjRC4ex6Ttk","durationMs":1026,"region":"iad1","maxMemoryUsed":32,"memorySize":1024,"message":"","projectId":"prj_nLtmkWiHzW9EPv20LiLufmtG1LNk"},{"TimeUTC":"2025-01-17 10:05:53","timestampInMs":1737108353072,"requestPath":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app/","requestMethod":"GET","responseStatusCode":-1,"requestId":"fcs8l-1737108351755-920ddd6c5492","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main.py","host":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentDomain":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentId":"dpl_DBBgxg2cVb9usJtdDVjRC4ex6Ttk","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/main.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, jsonify\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_nLtmkWiHzW9EPv20LiLufmtG1LNk"},{"TimeUTC":"2025-01-17 10:05:52","timestampInMs":1737108352927,"requestPath":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app/","requestMethod":"GET","responseStatusCode":-1,"requestId":"wlwzp-1737108351075-d3236eb7987e","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main.py","host":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentDomain":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentId":"dpl_DBBgxg2cVb9usJtdDVjRC4ex6Ttk","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/main.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, jsonify\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.\nTraceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/main.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, jsonify\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_nLtmkWiHzW9EPv20LiLufmtG1LNk"},{"TimeUTC":"2025-01-17 10:05:52","timestampInMs":1737108352012,"requestPath":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app/","requestMethod":"GET","responseStatusCode":500,"requestId":"fcs8l-1737108351755-920ddd6c5492","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main.py","host":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentDomain":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentId":"dpl_DBBgxg2cVb9usJtdDVjRC4ex6Ttk","durationMs":1039,"region":"iad1","maxMemoryUsed":32,"memorySize":1024,"message":"","projectId":"prj_nLtmkWiHzW9EPv20LiLufmtG1LNk"},{"TimeUTC":"2025-01-17 10:05:51","timestampInMs":1737108351628,"requestPath":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app/","requestMethod":"GET","responseStatusCode":-1,"requestId":"5hq9c-1737108350557-277f74caca58","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main.py","host":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentDomain":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentId":"dpl_DBBgxg2cVb9usJtdDVjRC4ex6Ttk","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/main.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, jsonify\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.\nTraceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/main.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, jsonify\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_nLtmkWiHzW9EPv20LiLufmtG1LNk"},{"TimeUTC":"2025-01-17 10:05:51","timestampInMs":1737108351621,"requestPath":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app/","requestMethod":"GET","responseStatusCode":-1,"requestId":"8j6nm-1737108350459-749215b750d8","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main.py","host":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentDomain":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentId":"dpl_DBBgxg2cVb9usJtdDVjRC4ex6Ttk","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/main.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, jsonify\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_nLtmkWiHzW9EPv20LiLufmtG1LNk"},{"TimeUTC":"2025-01-17 10:05:51","timestampInMs":1737108351112,"requestPath":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app/","requestMethod":"GET","responseStatusCode":500,"requestId":"wlwzp-1737108351075-d3236eb7987e","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main.py","host":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentDomain":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentId":"dpl_DBBgxg2cVb9usJtdDVjRC4ex6Ttk","durationMs":1011,"region":"iad1","maxMemoryUsed":62,"memorySize":1024,"message":"","projectId":"prj_nLtmkWiHzW9EPv20LiLufmtG1LNk"},{"TimeUTC":"2025-01-17 10:05:50","timestampInMs":1737108350594,"requestPath":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app/","requestMethod":"GET","responseStatusCode":500,"requestId":"8j6nm-1737108350459-749215b750d8","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main.py","host":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentDomain":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentId":"dpl_DBBgxg2cVb9usJtdDVjRC4ex6Ttk","durationMs":1009,"region":"iad1","maxMemoryUsed":62,"memorySize":1024,"message":"","projectId":"prj_nLtmkWiHzW9EPv20LiLufmtG1LNk"},{"TimeUTC":"2025-01-17 10:05:50","timestampInMs":1737108350591,"requestPath":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app/","requestMethod":"GET","responseStatusCode":500,"requestId":"5hq9c-1737108350557-277f74caca58","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main.py","host":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentDomain":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentId":"dpl_DBBgxg2cVb9usJtdDVjRC4ex6Ttk","durationMs":1011,"region":"iad1","maxMemoryUsed":32,"memorySize":1024,"message":"","projectId":"prj_nLtmkWiHzW9EPv20LiLufmtG1LNk"},{"TimeUTC":"2025-01-17 10:05:49","timestampInMs":1737108349418,"requestPath":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app/","requestMethod":"GET","responseStatusCode":-1,"requestId":"bjp7f-1737108348341-6367505b0713","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main.py","host":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentDomain":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentId":"dpl_DBBgxg2cVb9usJtdDVjRC4ex6Ttk","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/main.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, jsonify\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_nLtmkWiHzW9EPv20LiLufmtG1LNk"},{"TimeUTC":"2025-01-17 10:05:48","timestampInMs":1737108348990,"requestPath":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app/","requestMethod":"GET","responseStatusCode":-1,"requestId":"kkzgm-1737108347805-46039511ff02","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main.py","host":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentDomain":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentId":"dpl_DBBgxg2cVb9usJtdDVjRC4ex6Ttk","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/main.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, jsonify\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_nLtmkWiHzW9EPv20LiLufmtG1LNk"},{"TimeUTC":"2025-01-17 10:05:48","timestampInMs":1737108348377,"requestPath":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app/","requestMethod":"GET","responseStatusCode":500,"requestId":"bjp7f-1737108348341-6367505b0713","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main.py","host":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentDomain":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentId":"dpl_DBBgxg2cVb9usJtdDVjRC4ex6Ttk","durationMs":1022,"region":"iad1","maxMemoryUsed":32,"memorySize":1024,"message":"","projectId":"prj_nLtmkWiHzW9EPv20LiLufmtG1LNk"},{"TimeUTC":"2025-01-17 10:05:48","timestampInMs":1737108348372,"requestPath":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app/","requestMethod":"GET","responseStatusCode":-1,"requestId":"8j6nm-1737108346871-d2691d0f1664","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main.py","host":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentDomain":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentId":"dpl_DBBgxg2cVb9usJtdDVjRC4ex6Ttk","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/main.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, jsonify\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.\nTraceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/main.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, jsonify\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_nLtmkWiHzW9EPv20LiLufmtG1LNk"},{"TimeUTC":"2025-01-17 10:05:47","timestampInMs":1737108347956,"requestPath":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app/","requestMethod":"GET","responseStatusCode":500,"requestId":"kkzgm-1737108347805-46039511ff02","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main.py","host":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentDomain":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentId":"dpl_DBBgxg2cVb9usJtdDVjRC4ex6Ttk","durationMs":1015,"region":"iad1","maxMemoryUsed":62,"memorySize":1024,"message":"","projectId":"prj_nLtmkWiHzW9EPv20LiLufmtG1LNk"},{"TimeUTC":"2025-01-17 10:05:46","timestampInMs":1737108346906,"requestPath":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app/","requestMethod":"GET","responseStatusCode":500,"requestId":"8j6nm-1737108346871-d2691d0f1664","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main.py","host":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentDomain":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentId":"dpl_DBBgxg2cVb9usJtdDVjRC4ex6Ttk","durationMs":1036,"region":"iad1","maxMemoryUsed":32,"memorySize":1024,"message":"","projectId":"prj_nLtmkWiHzW9EPv20LiLufmtG1LNk"},{"TimeUTC":"2025-01-17 10:05:46","timestampInMs":1737108346667,"requestPath":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app/","requestMethod":"GET","responseStatusCode":-1,"requestId":"bjp7f-1737108344572-7453c8c3e6ed","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main.py","host":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentDomain":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentId":"dpl_DBBgxg2cVb9usJtdDVjRC4ex6Ttk","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/main.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, jsonify\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.\nTraceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/main.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, jsonify\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_nLtmkWiHzW9EPv20LiLufmtG1LNk"},{"TimeUTC":"2025-01-17 10:05:45","timestampInMs":1737108345821,"requestPath":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app/","requestMethod":"GET","responseStatusCode":-1,"requestId":"v694j-1737108344565-541e7046dd3b","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main.py","host":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentDomain":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentId":"dpl_DBBgxg2cVb9usJtdDVjRC4ex6Ttk","durationMs":-1,"region":"iad1","maxMemoryUsed":-1,"memorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/main.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, jsonify\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_nLtmkWiHzW9EPv20LiLufmtG1LNk"},{"TimeUTC":"2025-01-17 10:05:44","timestampInMs":1737108344799,"requestPath":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app/","requestMethod":"GET","responseStatusCode":500,"requestId":"bjp7f-1737108344572-7453c8c3e6ed","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main.py","host":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentDomain":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentId":"dpl_DBBgxg2cVb9usJtdDVjRC4ex6Ttk","durationMs":1029,"region":"iad1","maxMemoryUsed":32,"memorySize":1024,"message":"","projectId":"prj_nLtmkWiHzW9EPv20LiLufmtG1LNk"},{"TimeUTC":"2025-01-17 10:05:44","timestampInMs":1737108344797,"requestPath":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app/","requestMethod":"GET","responseStatusCode":500,"requestId":"v694j-1737108344565-541e7046dd3b","requestUserAgent":"vercel-screenshot/1.0","level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/main.py","host":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentDomain":"jadexi-pvnk2ychb-jadexelis-projects.vercel.app","deploymentId":"dpl_DBBgxg2cVb9usJtdDVjRC4ex6Ttk","durationMs":1002,"region":"iad1","maxMemoryUsed":62,"memorySize":1024,"message":"","projectId":"prj_nLtmkWiHzW9EPv20LiLufmtG1LNk"}]